[package]
name = "ps-database"
version = "0.2.0"
edition = "2021"

[dependencies]
rusqlite = {version = "0.26.1", features = ["chrono", "trace", "serde_json", "bundled"]}
ps-core = { path = "../ps-core" }